### ISSUE TITLE
Build a music player that pulls playlists of tracks based on artists a user follows

### ISSUE THREAD

**Issue by jlquaccia** [jlquaccia/the-music-project#27]

**Comment by jlquaccia** [comment]
Maybe playlists can consist of top 10 tracks by each artist in the playlist.

**Comment by jlquaccia** [comment]
Possible model associations:

**Option A:**
HABTM approach..

class User < ActiveRecord::Base
  has_many :playlists
  has_many :songs
end

class Playlist < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :songs
end

class Song < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :playlists
end

The table structure would consist of a `unique_id, song_id` and `playlist_id`

**Option B:**
has_many :through approach..
(In case I'd want to add any extra information to the playlist/song relationship model.  For example, song position.)

class User < ActiveRecord::Base
  has_many :playlists
  has_many :songs
end

class Playlist < ActiveRecord::Base
  belongs_to :user
  has_many :relationships
  has_many :songs, :through => relationships
end

class Song < ActiveRecord::Base
  belongs_to :user
  has_many :relationships
  has_many :playlists, :through => relationships
end

class Relationship < ActiveRecord::Base
  belongs_to :song
  belongs_to :playlist
end

**Comment by jlquaccia** [comment]
Review HABTM and has_many :through

**Comment by jlquaccia** [comment]
Find out the correct generation command to generate the model and associations listed above.  E.g. "rails g model Playlist.." etc.

**Comment by jlquaccia** [comment]
Play with Spotify endpoints and figuring out what to put inside the playlist.

**Comment by MichaelCPell** [comment]
nice!

On 31 October 2015 at 06:19, Jason Quaccia <notifications@github.com> wrote:

> Play with Spotify endpoints and figuring out what to put inside the
> playlist.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jlquaccia/the-music-project/issues/27#issuecomment-152698957>
> .
>



-- 
Michael Pell
1 (919) 408 7153
Skype: MichaelCPell

**Comment by jlquaccia** [comment]
Thanks man!  I actually just started to hit some road blocks today, gonna message you on Bloc.

**Comment by jlquaccia** [comment]
Looks like that 'Spotify Play Button' is the only way to play the full-length versions of tracks.  These play buttons redirect to the Spotify Web Player.

**Comment by MichaelCPell** [comment]
disaster

On 3 November 2015 at 18:01, Jason Quaccia <notifications@github.com> wrote:

> Looks like that 'Spotify Play Button' is the only way to play the
> full-length versions of tracks. These play buttons redirect to the Spotify
> Web Player.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jlquaccia/the-music-project/issues/27#issuecomment-153417949>
> .
>



-- 
Michael Pell
1 (919) 408 7153
Skype: MichaelCPell

**Comment by jlquaccia** [comment]
Haha.  We'll survive.
